# Generated by Django 2.2.6 on 2019-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='slug',
            field=models.CharField(default='main_settings', max_length=100, verbose_name='slug'),
        ),
    ]
