# Generated by Django 2.2.6 on 2019-10-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contactcard_status'),
        ('main', '0003_mainsettings_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='menu_settings', max_length=100, verbose_name='slug')),
                ('card_contacts', models.ManyToManyField(related_name='Контакты_меню', to='contacts.Contact')),
            ],
            options={
                'verbose_name': 'Контакты меню',
                'verbose_name_plural': 'Контакты меню',
            },
        ),
    ]
