# Generated by Django 2.2.6 on 2019-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menusettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('link', models.CharField(blank=True, max_length=600, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Соц сеть',
                'verbose_name_plural': 'Соц сети',
            },
        ),
    ]
