# Generated by Django 2.2.6 on 2020-01-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_footersocial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterSocial',
        ),
    ]
