# Generated by Django 2.2.6 on 2020-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_footersocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsettings',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='mainsettings',
            name='video',
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Политика обработки данных'),
        ),
    ]
