# Generated by Django 2.2.5 on 2019-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Название стать')),
                ('small_desc', models.TextField(null=True, verbose_name='Краткое описание')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Обложка')),
                ('banner', models.FileField(blank=True, null=True, upload_to='', verbose_name='Баннер')),
                ('text', models.TextField(null=True, verbose_name='Текст статьи')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата-начала')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
