# Generated by Django 2.2.5 on 2019-10-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('stocks', 'Свежие акции'), ('company', 'Новости компании'), ('pres', 'Пресса о нас')], max_length=500, null=True, verbose_name='Категория'),
        ),
    ]
