# Generated by Django 2.2.5 on 2019-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Свежие акции', 'Свежие акции'), ('Новости компании', 'Новости компании'), ('Пресса о нас', 'Пресса о нас')], max_length=500, null=True, verbose_name='Категория'),
        ),
    ]
