# Generated by Django 2.2.5 on 2019-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('card_name', models.CharField(max_length=300, verbose_name='Название')),
                ('card_desc', models.TextField(verbose_name='Описание')),
                ('card_img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фоновое изображение')),
                ('card_link', models.CharField(max_length=200, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
