# Generated by Django 2.2.6 on 2019-10-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='career', max_length=100, verbose_name='Ссылка')),
                ('bread_crumbs', models.CharField(max_length=200, null=True, verbose_name='Крошки')),
                ('page_name', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('page_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Страница "Карьера"',
                'verbose_name_plural': 'Страница "Карьера"',
            },
        ),
        migrations.CreateModel(
            name='PageOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='oil', max_length=100, verbose_name='Ссылка')),
                ('bread_crumbs', models.CharField(max_length=200, null=True, verbose_name='Крошки')),
                ('page_name', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('page_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Страница "О масле"',
                'verbose_name_plural': 'Страница "О масле"',
            },
        ),
        migrations.CreateModel(
            name='PageProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='production', max_length=100, verbose_name='Ссылка')),
                ('bread_crumbs', models.CharField(max_length=200, null=True, verbose_name='Крошки')),
                ('page_name', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('page_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Страница "Производство"',
                'verbose_name_plural': 'Страница "Производство"',
            },
        ),
        migrations.CreateModel(
            name='PageTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='team', max_length=100, verbose_name='Ссылка')),
                ('page_name', models.CharField(max_length=200, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': 'Страница "Команда"',
                'verbose_name_plural': 'Страница "Команда"',
            },
        ),
    ]
