# Generated by Django 2.2.6 on 2019-10-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_pagecareer_pageoil_pageproduction_pageteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('post', models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность')),
                ('mail', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
    ]
