# Generated by Django 2.2.6 on 2019-10-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Преимущество')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
