# Generated by Django 2.2.6 on 2019-10-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr', models.CharField(choices=[('office', 'Офис'), ('production', 'Производство')], max_length=500, null=True, verbose_name='Атрибут')),
                ('type', models.CharField(choices=[('full_day', 'Полный день'), ('part_day', 'Неполный день'), ('switch_day', 'Сменная работа'), ('once_day', 'Разовая работа')], max_length=500, null=True, verbose_name='Тип работы')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('price', models.CharField(blank=True, max_length=600, null=True, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
