# Generated by Django 2.2.6 on 2019-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='atr',
            field=models.CharField(choices=[('Офис', 'Офис'), ('Производство', 'Производство')], max_length=500, null=True, verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.CharField(choices=[('Полный день', 'Полный день'), ('Неполный день', 'Неполный день'), ('Сменная работа', 'Сменная работа'), ('Разовая работ', 'Разовая работа')], max_length=500, null=True, verbose_name='Тип работы'),
        ),
    ]
