# Generated by Django 2.2.6 on 2020-01-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20191024_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageproduction',
            name='check_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='check_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='clear_text_1',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 1 очистка масла'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='clear_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2 очистка масла'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='clear_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='clear_title_1',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 1'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='clear_title_2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 2'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='cold_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='cold_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='filter_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='filter_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='first_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='first_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='oil_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='oil_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='oil_title_1',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 1'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='oil_title_small',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_2_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст второго блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_2_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название второго блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_3_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст третьего блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_3_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название третьего блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_4_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст четвертого блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_4_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название четвертого блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_5_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пятого блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_5_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название пятого блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_first_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст первого блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_first_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название первого блока'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
    ]
