# Generated by Django 2.2.6 on 2020-01-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200114_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageoil',
            name='choice_item_1_1',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_item_1_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_item_2_1',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_item_2_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_text_bottom',
            field=models.TextField(blank=True, null=True, verbose_name='Текст снизу'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_title_1',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_title_2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='cold_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='cold_text_1',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='cold_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='cold_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='first_text_1',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='first_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='first_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_text_3',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_text_4',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 4'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_title_1',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_title_2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_title_3',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 3'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_title_4',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 4'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='proof_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='proof_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='proof_title_1',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название 1'),
        ),
    ]
