# Generated by Django 2.2.6 on 2020-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20200114_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageoil',
            name='choice_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='choice_img_big',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Большая картинка>'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='cold_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='cold_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='first_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='first_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='myth_img_big',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Большая картинка>'),
        ),
        migrations.AddField(
            model_name='pageoil',
            name='proof_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
