# Generated by Django 2.2.6 on 2020-03-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20200320_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageproduction',
            name='check_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='clear_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='clear_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='cold_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='filter_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='first_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='first_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='first_img_big',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Большая картинка>'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='oil_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='oil_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_img_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_img_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_img_4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 4'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_img_5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка 5'),
        ),
        migrations.AddField(
            model_name='pageproduction',
            name='press_img_big',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Большая картинка'),
        ),
    ]
