# Generated by Django 2.2.5 on 2019-10-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(verbose_name='Дата')),
                ('report_name', models.CharField(max_length=200, verbose_name='Название')),
                ('report_desc', models.TextField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Презентация/Отчет',
                'verbose_name_plural': 'Презентации и Отчеты',
            },
        ),
    ]
