# Generated by Django 2.2.5 on 2019-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_report_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
