# Generated by Django 2.2.5 on 2019-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bread_crumbs',
            field=models.CharField(max_length=200, null=True, verbose_name='Крошки'),
        ),
    ]
