# Generated by Django 2.2.5 on 2019-10-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_car_car2_engine_engine2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car2',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Engine2'),
        ),
    ]
