# Generated by Django 2.2.5 on 2019-10-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20191002_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='PageForPartners',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='engine',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Car2',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.DeleteModel(
            name='Engine2',
        ),
    ]
