# Generated by Django 2.2.5 on 2019-10-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20191003_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageforpartners',
            options={'verbose_name': 'Страница "Партнерам"', 'verbose_name_plural': 'Страница "Партнерам"'},
        ),
    ]
