# Generated by Django 2.2.5 on 2019-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_pageretail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('bread_crumbs', models.CharField(max_length=200, null=True, verbose_name='Крошки')),
                ('page_name', models.CharField(max_length=200, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': 'Страница "Ресторанам"',
                'verbose_name_plural': 'Страница "Ресторанам"',
            },
        ),
    ]
