# Generated by Django 2.2.5 on 2019-10-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_card_card_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageforpartners',
            name='page_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='pagerestaurant',
            name='page_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='pageretail',
            name='page_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фон'),
        ),
    ]
