# Generated by Django 2.2.5 on 2019-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20191006_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default=1, max_length=1, verbose_name='Type'),
        ),
    ]
