# Generated by Django 2.2.5 on 2019-10-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_card_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
    ]
