# Generated by Django 2.2.5 on 2019-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_remove_card_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Партнер')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('country', models.CharField(choices=[('ru', 'Россия'), ('ch', 'Китай'), ('uar', 'ЮАР'), ('canada', 'Канада'), ('fr', 'Франция'), ('it', 'Италия')], max_length=500, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
