# Generated by Django 2.2.5 on 2019-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.CharField(choices=[('ru', 'Россия'), ('ch', 'Китай'), ('uar', 'ЮАР'), ('canada', 'Канада'), ('fr', 'Франция'), ('it', 'Италия')], max_length=500, null=True, verbose_name='Cтрана'),
        ),
    ]
