# Generated by Django 2.2.5 on 2019-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contactcard_status'),
        ('business', '0019_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='contacts',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
