# Generated by Django 2.2.5 on 2019-10-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contactcard_status'),
        ('business', '0022_auto_20191010_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageretail',
            name='contacts_2',
            field=models.ManyToManyField(related_name='second_contact', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='pageretail',
            name='contacts_name_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название контакта 2'),
        ),
        migrations.AlterField(
            model_name='pageretail',
            name='contacts_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название контакта 2'),
        ),
    ]
