# Generated by Django 2.2.6 on 2019-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_auto_20191010_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageforpartners',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Презентация'),
        ),
        migrations.AddField(
            model_name='pageretail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Презентация'),
        ),
    ]
