# Generated by Django 2.2.6 on 2020-01-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20191024_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerestaurant',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='pagerestaurant',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='pagerestaurant',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
