# Generated by Django 2.2.5 on 2019-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Название')),
                ('img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('desc', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
    ]
