# Generated by Django 2.2.5 on 2019-10-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactcard_card_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='card_desc',
        ),
        migrations.RemoveField(
            model_name='contactcard',
            name='card_name',
        ),
    ]
