# Generated by Django 2.2.5 on 2019-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20191009_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Название'),
        ),
    ]
