# Generated by Django 2.2.5 on 2019-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='card_contacts',
            field=models.ManyToManyField(related_name='Контакты', to='contacts.Contact'),
        ),
    ]
