# Generated by Django 2.2.5 on 2019-10-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20191009_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='card_contacts',
            field=models.ManyToManyField(limit_choices_to=3, related_name='Контакты', to='contacts.Contact'),
        ),
    ]
