# Generated by Django 2.2.5 on 2019-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20191009_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='card_contacts',
            field=models.ManyToManyField(limit_choices_to=3, to='contacts.Contact'),
        ),
    ]
