# Generated by Django 2.2.5 on 2019-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20191009_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('link', 'Cсылка'), ('adr', 'Адрес')], max_length=600, null=True, verbose_name='Тип'),
        ),
    ]
