# Generated by Django 2.2.5 on 2019-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
