# Generated by Django 2.2.5 on 2019-10-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20191009_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='status',
            field=models.CharField(choices=[('main', 'Основные'), ('other', 'Другие контакты')], max_length=600, null=True, verbose_name='Тип'),
        ),
    ]
