# Generated by Django 2.2.6 on 2020-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_socialfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=900, null=True, verbose_name='Ссылка')),
                ('name', models.CharField(max_length=600, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Контакт в подвале',
                'verbose_name_plural': 'Контакты сети в подвале',
            },
        ),
    ]
