# Generated by Django 2.2.6 on 2020-01-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_footercontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercontact',
            options={'verbose_name': 'Контакт в подвале', 'verbose_name_plural': 'Контакты в подвале'},
        ),
    ]
