# Generated by Django 2.2.6 on 2020-01-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20200111_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя контакта'),
        ),
    ]
