# Generated by Django 2.2.6 on 2020-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=500, null=True, verbose_name='Имя контакта'),
        ),
    ]
