# Generated by Django 2.2.6 on 2020-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20200111_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='title', max_length=500, verbose_name='Имя контакта'),
        ),
    ]
